### ISSUE TITLE
Add custom welcome message for new users

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton-bot#52]
Use the `team_join` event to send new user's a PM with lots of info from @tmarconi 

Example for reference - https://api.slack.com/best-practices/blueprints/new-user-notification
Example for DM'ing a user w/ ruby - https://github.com/slack-ruby/slack-ruby-bot/issues/112#issuecomment-279061006
More comprehensive ruby example - https://github.com/slackapi/Slack-Ruby-Onboarding-Tutorial/blob/master/README.md#building-an-onboarding-bot-in-ruby-using-slacks-events-api
`team_join` payload https://github.com/slackapi/Slack-Ruby-Onboarding-Tutorial/blob/master/Section-3.md#add-the-other-event-handlers

- [x] Get copy from Tim
- [x] Figure out a test strategy (how we can create new users to test this properly?)
- [x] Write code, test, ship, 💰

**Comment by tmarconi** [comment]
The copy is a Slack post, happy to provide whenever you need it.

**Comment by mcritchlow** [comment]
Fixed via #61
